import sqlite3

conn = sqlite3.connect('plant_result.db')

c = conn.cursor()

'''c.execute("CREATE TABLE sampletb(id integer,name TEXT,reason TEXT,Treatment TEXT)")
c.execute("INSERT INTO sampletb VALUES(1, 'Pepper bell Bacterial spot','Bacterial leaf spot is spread by splashing rain and working with wet, infected plants.The bacterium is spread by plant debris in the soil and through infected seeds.','Crop rotation can help prevent bacterial leaf spot. Do not compost plant debris that may contain the disease. Reduce the splatter by using a soaker hose and avoiding overhead watering.')")
c.execute("INSERT INTO sampletb VALUES(3,'Potato Early Blight','Early blight can occur any time throughout the growing season. High temperatures (80-85˚F.) and wet, humid conditions promote its rapid spread. In many cases, poorly nourished or stressed plants are attacked.','apply copper-based fungicides early, two weeks before disease normally appears or when weather forecasts predict a long period of wet weather. Alternatively, begin treatment when disease first appears, and repeat every 7-10 days for as long as needed.')")
c.execute("INSERT INTO sampletb VALUES(4,'Potato Late Blight','Instead the spores are introduced by infected tubers, transplants or seeds. Wind will also carry the disease from nearby gardens. Warm temperatures (70-80˚F) and wet, humid conditions promote its rapid spread.','Apply a copper based fungicide (2 oz/ gallon of water) every 7 days or less, following heavy rain or when the amount of disease is increasing rapidly. If possible, time applications so that at least 12 hours of dry weather follows application.')")
c.execute("INSERT INTO sampletb VALUES(6,'Tomato Bacterial Spot','It is especially severe in warm, wet and windy conditions, causing plants to lose their leaves.','Use copper fungicides, or copper plus mancozeb. It is very important to have healthy seedlings free from bacterial spot, so spraying should start in the nursery, and continue at 7-10 day intervals in the field. Spraying early, when the plants are young, is especially important as in wet, windy weather, sprays alone often fail to give adequate control.')")
c.execute("INSERT INTO sampletb VALUES(7,'Tomato Early Blight','Spread over short distances occurs when spores are moved plant-to-plant in wind, rain and overhead irrigation water. Survival occurs in crop remains, and also on seed. Favourable conditions for the disease are warm, humid weather with heavy dews or rains.','Use protectant fungicides, mancozeb, chlorothalonil or copper products. Systemic products are available, e.g., strobilurins, although they are expensive and, if used too often, the fungus may develop resistance to them.')")
c.execute("INSERT INTO sampletb VALUES(8,'Tomato Late Blight','Late blight fungi grow best in high relative humidities and temperature ranges. Warm and dry summer weather can bring the soread of the disease to a halt.','Use fungicide sprays based on mandipropamid, chlorothalonil, fluazinam, mancozeb to combat late blight.')")
c.execute("INSERT INTO sampletb VALUES(9,'Tomato Leaf Mold','In can infect when the leaf surface is wet. Leaf mold can develop over a wide temperature range (39 – 90 F). Optimal temperature is 72 – 75 F.','The fungi Acremonium strictum, dicyma pulvinata, Trichoderma harzianum or  T.viride and Trichothecium roseum are antagonistic to M. fulva and could be used to reduce its spread. Apple-cider, garlic or mild sprays and vinegar mix can be used to treat the mold.')")
c.execute("INSERT INTO sampletb VALUES(10,'Tomato Septoria Leaf Spot','is spread to the plants by both water and wind, usually splashing up on the plants from the soil. Warm (60 to 80 F), damp conditions are the most favorable for Septoria leaf spot to develop.','Fungicides containing either copper or potassium bicarbonate will help prevent the spreading of the disease. Spraying any fungicide, it is advisable to mix it with INTEGRA 3ml/20l, which improves the efficacy of the respective fungicide.')")
c.execute("INSERT INTO sampletb VALUES(11,'Tomato Spider Mites Two_spotted Spider Mite','Spider mites are most common in hot, dry conditions, especially where their natural enemies have been killed off by insecticide use.','BotaniGard ES is a highly effective biological insecticide containing Beauveria bassiana, an entomopathogenic fungus that attacks a long-list of troublesome crop pests – even resistant strains! Weekly applications can prevent insect population explosions and provide protection equal to or better than conventional chemical pesticides.')")
c.execute("INSERT INTO sampletb VALUES(12,'Tomato Target Spot','The source of the fungus is from other crops, the remains of the previous crop and, perhaps, other host species. The spores are spread by wind-blown rain, and if windy wet weather continues for a few days, spread is fast and plants lose their leaves quickly.','The products to use are chlorothalonil, copper oxychloride or mancozeb. Treatment should start when the first spots are seen and continue at 10-14-day intervals until 3-4 weeks before last harvest. It is important to spray both sides of the leaves.')")
c.execute("INSERT INTO sampletb VALUES(13,'Tomato Tomato Yellow Leaf Curl Virus','The virus lives in the plant and is spread from plant to plant by whiteflies, which feed on the plants.','Imidacloprid should be sprayed on the entire plant and below the leaves; eggs and flies are often found below the leaves. Spray every 14-21 days and rotate on a monthly basis with Abamectin so that the whiteflies do not build-up resistance to chemicals.')")
c.execute("INSERT INTO sampletb VALUES(14,'Tomato Tomato mosaic virus','Mosaic virus overwinters on perennial weeds and is spread by insects that feed on them. Aphids, leafhoppers, whiteflies and cucumber beetles are common garden pests that can transmit this disease.','Fungicides will NOT treat this viral disease.Spot treat with least-toxic, natural pest control products, such as Safer Soap, Bon-Neem and diatomaceous earth, to reduce the number of disease carrying insects.')")
'''
index = 4
c.execute("SELECT * FROM sampletb where id=index")
print(c.fetchall())

conn.commit()
c.close()
conn.close()
